services:
  app:
    build: .
    container_name: symfony-app
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
      - mercure

  mysql:
    image: mysql:8.0
    container_name: symfony-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prueba
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - mysql_data:/var/lib/mysql

  mercure:
    image: dunglas/mercure
    container_name: symfony-mercure
    restart: unless-stopped
    environment:
      SERVER_NAME: ':80'
      MERCURE_PUBLISHER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_SUBSCRIBER_JWT_KEY: '!ChangeThisMercureHubJWTSecretKey!'
      MERCURE_EXTRA_DIRECTIVES: |
        anonymous
        cors_origins *
    ports:
      - "3000:80"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: symfony-phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql_data:
